version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongousername
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword

  mongo-express:
    image: mongo-express
    ports: 
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongousername
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongopassword
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb